In [1]:
import json  
import pandas as pd  
from pandas.io.json import json_normalize  
import requests
from tabulate import tabulate
from sklearn.cluster import KMeans
import random
import numpy as np
import pandas as pd
import folium
import warnings
warnings.filterwarnings('ignore')
import os
os.environ.keys()

KeysView(environ({'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\lenovo\\AppData\\Roaming', 'CHOCOLATEYINSTALL': 'C:\\ProgramData\\chocolatey', 'CHOCOLATEYLASTPATHUPDATE': '132630958274327839', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'LAPTOP-EVI9LEN4', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'CONDA_DEFAULT_ENV': 'C:\\Users\\lenovo\\Desktop\\Geo\\Geo\\env', 'CONDA_EXE': 'C:\\Users\\lenovo\\miniconda3\\Scripts\\conda.exe', 'CONDA_PREFIX': 'C:\\Users\\lenovo\\Desktop\\Geo\\Geo\\env', 'CONDA_PREFIX_1': 'C:\\Users\\lenovo\\miniconda3', 'CONDA_PROMPT_MODIFIER': '(C:\\Users\\lenovo\\Desktop\\Geo\\Geo\\env) ', 'CONDA_PYTHON_EXE': 'C:\\Users\\lenovo\\miniconda3\\python.exe', 'CONDA_SHLVL': '2', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\lenovo', 'INTELLIJ IDEA COMMUNITY EDITION': 'C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2021.1\\bin;', 'LOCALAPPDATA': 'C:\\Users\\lenovo\\AppData\\Local', 'LOGONSERVER': '\\\\LAPTOP-EVI9LEN4', 'NUMBER_OF_PROCESSORS': '8', 'ONEDRIVE': 'C:\\Users\\lenovo\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\Users\\lenovo\\Desktop\\Geo\\Geo\\env;C:\\Users\\lenovo\\Desktop\\Geo\\Geo\\env\\Library\\mingw-w64\\bin;C:\\Users\\lenovo\\Desktop\\Geo\\Geo\\env\\Library\\usr\\bin;C:\\Users\\lenovo\\Desktop\\Geo\\Geo\\env\\Library\\bin;C:\\Users\\lenovo\\Desktop\\Geo\\Geo\\env\\Scripts;C:\\Users\\lenovo\\Desktop\\Geo\\Geo\\env\\bin;C:\\Users\\lenovo\\miniconda3\\condabin;C:\\Program Files (x86)\\VMware\\VMware Player\\bin;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\Git\\cmd;C:\\MinGW\\bin;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\nodejs;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn;C:\\Program Files\\Azure Data Studio\\bin;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\Tools\\Binn;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn;C:\\Program Files\\Microsoft SQL Server\\150\\DTS\\Binn;C:\\Program Files\\dotnet;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn;C:\\Program Files\\MySQL\\MySQL Server 8.0\\bin;C:\\Program Files\\MySQL\\MySQL Shell 8.0\\bin;C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python39\\Scripts;C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python39;C:\\Users\\lenovo\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\lenovo\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\lenovo\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin;C:\\Program Files\\Java\\jdk-16\\bin;C:\\Program Files\\JetBrains\\WebStorm 2021.1\\bin;.;C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2021.1\\bin;.;C:\\Users\\lenovo\\AppData\\Roaming\\npm;C:\\Program Files\\MongoDB\\Server\\5.0\\bin;C:\\Program Files\\Azure Data Studio\\bin;C:\\Users\\lenovo\\.dotnet\\tools;C:\\Program Files\\heroku\\bin', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 140 Stepping 1, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '8c01', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PROMPT': '(C:\\Users\\lenovo\\Desktop\\Geo\\Geo\\env) $P$G', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\Tools\\PowerShell\\Modules\\', 'PUBLIC': 'C:\\Users\\Public', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\WINDOWS', 'TEMP': 'C:\\Users\\lenovo\\AppData\\Local\\Temp', 'TMP': 'C:\\Users\\lenovo\\AppData\\Local\\Temp', 'USERDOMAIN': 'LAPTOP-EVI9LEN4', 'USERDOMAIN_ROAMINGPROFILE': 'LAPTOP-EVI9LEN4', 'USERNAME': 'lenovo', 'USERPROFILE': 'C:\\Users\\lenovo', 'VBOX_MSI_INSTALL_PATH': 'C:\\Program Files\\Oracle\\VirtualBox\\', 'VS160COMCOMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\', 'WEBSTORM': 'C:\\Program Files\\JetBrains\\WebStorm 2021.1\\bin;', 'WINDIR': 'C:\\WINDOWS', 'ZES_ENABLE_SYSMAN': '1', 'PYDEVD_USE_FRAME_EVAL': 'NO', 'JPY_INTERRUPT_EVENT': '2204', 'IPY_INTERRUPT_EVENT': '2204', 'JPY_PARENT_PID': '2360', 'TERM': 'xterm-color', 'CLICOLOR': '1', 'PAGER': 'cat', 'GIT_PAGER': 'cat', 'MPLBACKEND': 'module://matplotlib_inline.backend_inline', 'KMP_DUPLICATE_LIB_OK': 'True', 'KMP_INIT_AT_FORK': 'FALSE'}))

In [14]:
#Fetching data form HERE API for IIT Bombay
url = 'https://discover.search.hereapi.com/v1/discover?in=circle:19.1334,72.9133;r=10000&q=apartment&apiKey=uJHMEjeagmFGldXp661-pDMf4R-PxvWIu7I68UjYC5Q'
data = requests.get(url).json()
d=json_normalize(data['items'])
d.to_csv('api-data/apartment.csv')
d

,title,id,language,ontologyId,resultType,access,distance,categories,address.label,address.countryCode,...,address.county,address.city,address.district,address.street,address.postalCode,position.lat,position.lng,contacts,address.subdistrict,address.houseNumber
0,Dharamraj,here:pds:place:356te7ug-aab7da0959a549568e2d53...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.12545, 'lng': 72.91935}]",1086,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","Dharamraj, Hare Krishna Road, Powai, Mumbai 40...",IND,...,Mumbai Suburban,Mumbai,Powai,Hare Krishna Road,400076,19.12548,72.91935,NaN,NaN,NaN
1,Pajasa Apartments,here:pds:place:356te7ug-2d6f7d8713484a3c822ff1...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.12339, 'lng': 72.91275}]",1115,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","Pajasa Apartments, Central Avenue, Hiranandani...",IND,...,Mumbai Suburban,Mumbai,Powai,Central Avenue,400076,19.12339,72.91274,"[{'phone': [{'value': '+912269999891'}], 'www'...",Hiranandani Gardens,NaN
2,Scorpio House,here:pds:place:356te7ug-3fc1a164b55c7471dfef61...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.11933, 'lng': 72.91227}]",1568,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","Scorpio House, Central Avenue, Hiranandani Gar...",IND,...,Mumbai Suburban,Mumbai,Powai,Central Avenue,400076,19.11933,72.91227,NaN,Hiranandani Gardens,NaN
3,Andheri East Service Apartments,here:pds:place:356te7uf-0d5db6077151dcd2369691...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.11747, 'lng': 72.88374}]",3576,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","Andheri East Service Apartments, Marol, Andher...",IND,...,Mumbai Suburban,Mumbai,Andheri East,NaN,400059,19.11746,72.88374,"[{'phone': [{'value': '+919820049408'}], 'www'...",Marol,NaN
4,Aghadi Nagar CHS,here:pds:place:356te7v5-ea19989e14a440f9b83865...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.16289, 'lng': 72.93287}]",3860,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","Aghadi Nagar CHS, Dargah Road, Bhandup West, M...",IND,...,Mumbai Suburban,Mumbai,Bhandup West,Dargah Road,400078,19.16278,72.93287,[{'mobile': [{'value': '+919324060902'}]}],NaN,NaN
5,Irel Officers Apartment,here:pds:place:356te7ue-e65c876ed64c4bcd89ce87...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.09585, 'lng': 72.91369}]",4170,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","Irel Officers Apartment, Damodar Park Road, Da...",IND,...,Mumbai Suburban,Mumbai,Ghatkopar West,Damodar Park Road,400086,19.09590,72.91356,[{'phone': [{'value': '+912224220843'}]}],Damodar Park,NaN
6,Vic Mon B Wing,here:pds:place:356te7ud-e1d26697d0d54f3eb62c7e...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.11162, 'lng': 72.87512}]",4689,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","Vic Mon B Wing, Church Road, J B Nagar, Andher...",IND,...,Mumbai Suburban,Mumbai,Andheri East,Church Road,400059,19.11167,72.87505,NaN,J B Nagar,NaN
7,Ramkrishna,here:pds:place:356te7vh-7a6a646cb9f14688aae4bc...,en-GB,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.16653, 'lng': 72.95591}]",5790,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","Ramkrishna, Hutatma Chapekar Bhandu Marg, Salv...",IND,...,Mumbai Suburban,Mumbai,Mulund East,Hutatma Chapekar Bhandu Marg,400081,19.16650,72.95585,NaN,Salvi Wadi,NaN
8,Skiffle CHS,here:pds:place:356te7ue-44bc5a50b70e4079ba6ba5...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.07813, 'lng': 72.91169}]",6147,"[{'id': '900-9300-0221', 'name': 'Residential ...","Skiffle CHS, Vallabh Baug Lane, Ghatkopar East...",IND,...,Mumbai Suburban,Mumbai,Ghatkopar East,Vallabh Baug Lane,400077,19.07814,72.91175,NaN,NaN,NaN
9,Ganash,here:pds:place:356te7vh-c25b431bc219440580a988...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.17182, 'lng': 72.9557}]",6168,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","Ganash, Gopal Krishna Gokhale Road, Mulund Eas...",IND,...,Mumbai Suburban,Mumbai,Mulund East,Gopal Krishna Gokhale Road,400081,19.17180,72.95568,NaN,NaN,NaN
10,Royal Palms Estate & Properties,here:pds:place:356te7v6-7424bd059ac945ec9d5623...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.16285, 'lng': 72.85787}]",6680,"[{'id': '700-7400-0145', 'name': 'Real Estate ...","Royal Palms Estate & Properties, Goregaon East...",IND,...,Mumbai Suburban,Mumbai,Goregaon East,NaN,400063,19.16285,72.85787,"[{'phone': [{'value': '+912261462000'}], 'www'...",NaN,NaN
11,Sana Guest House,here:pds:place:356te7uc-643359fa033fcf8daed1ed...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.12397, 'lng': 72.84666}]",7069,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","Sana Guest House, 68 S V Road, Andheri West, M...",IND,...,Mumbai Suburban,Mumbai,Andheri West,S V Road,400058,19.12396,72.84676,[{'phone': [{'value': '+912232156639'}]}],NaN,68
12,Twinkle Service Apartment,here:pds:place:356te7uc-7c88537101df4ea6a68850...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.14636, 'lng': 72.84589}]",7222,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","Twinkle Service Apartment, Oshiwara Garden Roa...",IND,...,Mumbai Suburban,Mumbai,Jogeshwari West,Oshiwara Garden Road,400102,19.14620,72.84590,"[{'phone': [{'value': '+919819099019'}], 'www'...",Oshiwara Garden,NaN
13,Bandy's Riversong,here:pds:place:356te7u9-5649d8369dc442aaa7130b...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.10771, 'lng': 72.84909}]",7322,"[{'id': '500-5000-0053', 'name': 'Hotel', 'pri...","Bandy's Riversong, Vile Parle East, Mumbai 400...",IND,...,Mumbai Suburban,Mumbai,Vile Parle East,NaN,400057,19.10781,72.84909,"[{'phone': [{'value': '+919820094164'}], 'www'...",NaN,NaN
14,Strawberry Vacations,here:pds:place:356te7u9-956d7d7d767748078ab88e...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.09623, 'lng': 72.85419}]",7460,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","Strawberry Vacations, Nehru Road, Vile Parle E...",IND,...,Mumbai Suburban,Mumbai,Vile Parle East,Nehru Road,400099,19.09623,72.85419,"[{'phone': [{'value': '+919664666457'}], 'www'...",NaN,NaN
15,LOTUS Colony Aarogy Kendra,here:pds:place:356te7u7-3cf7a09df2294d679aa603...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.06424, 'lng': 72.91839}]",7691,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","LOTUS Colony Aarogy Kendra, Shivaji Nagar-Lotu...",IND,...,Mumbai Suburban,Mumbai,Govandi West,NaN,400043,19.06441,72.91849,NaN,Shivaji Nagar-Lotus Colony,NaN
16,La Maison Hospitality,here:pds:place:356te7u9-d7b0a51c06674bbebbb9cb...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.10195, 'lng': 72.84543}]",7937,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","La Maison Hospitality, 1 Parleshwar Marg, Navp...",IND,...,Mumbai Suburban,Mumbai,Vile Parle East,Parleshwar Marg,400057,19.10186,72.84553,"[{'phone': [{'value': '+919930122614'}], 'www'...",Navpada,1
17,Oshi,here:pds:place:356te7uc-7a52de251c97490b875666...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.14885, 'lng': 72.83944}]",7956,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","Oshi, Oshiwara, Jogeshwari West, Mumbai 400102...",IND,...,Mumbai Suburban,Mumbai,Jogeshwari West,NaN,400102,19.14881,72.83934,NaN,Oshiwara,NaN
18,BBJ Verona Proposed,here:pds:place:356te7uc-70596e9c0e29441e8897bb...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.14886, 'lng': 72.8389}]",7991,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","BBJ Verona Proposed, Oshiwara, Jogeshwari West...",IND,...,Mumbai Suburban,Mumbai,Jogeshwari West,NaN,400102,19.14887,72.83901,NaN,Oshiwara,NaN
19,Bhagat Enterprises,here:pds:place:356te7uu-e5b5ef67de46464d94b444...,en,here:cm:ontology:apartment_rental_flat_rental,place,"[{'lat': 19.12502, 'lng': 72.98942}]",8056,"[{'id': '700-7200-0324', 'name': 'Apartment/Fl...","Bhagat Enterprises, Gagangiri Maharaj Marg, Se...",IND,...,Thane,Navi Mumbai,Ghansoli,Gagangiri Maharaj Marg,400701,19.12503,72.98947,[{'phone': [{'value': '+919987140408'}]}],Sector 15,NaN

In [15]:
#Cleaning API data
d2=d[['title','address.label','distance','access','position.lat','position.lng','address.postalCode','contacts','id']]
d2.to_csv('api-data/cleaned_apartment.csv')
d2

,title,address.label,distance,access,position.lat,position.lng,address.postalCode,contacts,id
0,Dharamraj,"Dharamraj, Hare Krishna Road, Powai, Mumbai 40...",1086,"[{'lat': 19.12545, 'lng': 72.91935}]",19.12548,72.91935,400076,NaN,here:pds:place:356te7ug-aab7da0959a549568e2d53...
1,Pajasa Apartments,"Pajasa Apartments, Central Avenue, Hiranandani...",1115,"[{'lat': 19.12339, 'lng': 72.91275}]",19.12339,72.91274,400076,"[{'phone': [{'value': '+912269999891'}], 'www'...",here:pds:place:356te7ug-2d6f7d8713484a3c822ff1...
2,Scorpio House,"Scorpio House, Central Avenue, Hiranandani Gar...",1568,"[{'lat': 19.11933, 'lng': 72.91227}]",19.11933,72.91227,400076,NaN,here:pds:place:356te7ug-3fc1a164b55c7471dfef61...
3,Andheri East Service Apartments,"Andheri East Service Apartments, Marol, Andher...",3576,"[{'lat': 19.11747, 'lng': 72.88374}]",19.11746,72.88374,400059,"[{'phone': [{'value': '+919820049408'}], 'www'...",here:pds:place:356te7uf-0d5db6077151dcd2369691...
4,Aghadi Nagar CHS,"Aghadi Nagar CHS, Dargah Road, Bhandup West, M...",3860,"[{'lat': 19.16289, 'lng': 72.93287}]",19.16278,72.93287,400078,[{'mobile': [{'value': '+919324060902'}]}],here:pds:place:356te7v5-ea19989e14a440f9b83865...
5,Irel Officers Apartment,"Irel Officers Apartment, Damodar Park Road, Da...",4170,"[{'lat': 19.09585, 'lng': 72.91369}]",19.09590,72.91356,400086,[{'phone': [{'value': '+912224220843'}]}],here:pds:place:356te7ue-e65c876ed64c4bcd89ce87...
6,Vic Mon B Wing,"Vic Mon B Wing, Church Road, J B Nagar, Andher...",4689,"[{'lat': 19.11162, 'lng': 72.87512}]",19.11167,72.87505,400059,NaN,here:pds:place:356te7ud-e1d26697d0d54f3eb62c7e...
7,Ramkrishna,"Ramkrishna, Hutatma Chapekar Bhandu Marg, Salv...",5790,"[{'lat': 19.16653, 'lng': 72.95591}]",19.16650,72.95585,400081,NaN,here:pds:place:356te7vh-7a6a646cb9f14688aae4bc...
8,Skiffle CHS,"Skiffle CHS, Vallabh Baug Lane, Ghatkopar East...",6147,"[{'lat': 19.07813, 'lng': 72.91169}]",19.07814,72.91175,400077,NaN,here:pds:place:356te7ue-44bc5a50b70e4079ba6ba5...
9,Ganash,"Ganash, Gopal Krishna Gokhale Road, Mulund Eas...",6168,"[{'lat': 19.17182, 'lng': 72.9557}]",19.17180,72.95568,400081,NaN,here:pds:place:356te7vh-c25b431bc219440580a988...
10,Royal Palms Estate & Properties,"Royal Palms Estate & Properties, Goregaon East...",6680,"[{'lat': 19.16285, 'lng': 72.85787}]",19.16285,72.85787,400063,"[{'phone': [{'value': '+912261462000'}], 'www'...",here:pds:place:356te7v6-7424bd059ac945ec9d5623...
11,Sana Guest House,"Sana Guest House, 68 S V Road, Andheri West, M...",7069,"[{'lat': 19.12397, 'lng': 72.84666}]",19.12396,72.84676,400058,[{'phone': [{'value': '+912232156639'}]}],here:pds:place:356te7uc-643359fa033fcf8daed1ed...
12,Twinkle Service Apartment,"Twinkle Service Apartment, Oshiwara Garden Roa...",7222,"[{'lat': 19.14636, 'lng': 72.84589}]",19.14620,72.84590,400102,"[{'phone': [{'value': '+919819099019'}], 'www'...",here:pds:place:356te7uc-7c88537101df4ea6a68850...
13,Bandy's Riversong,"Bandy's Riversong, Vile Parle East, Mumbai 400...",7322,"[{'lat': 19.10771, 'lng': 72.84909}]",19.10781,72.84909,400057,"[{'phone': [{'value': '+919820094164'}], 'www'...",here:pds:place:356te7u9-5649d8369dc442aaa7130b...
14,Strawberry Vacations,"Strawberry Vacations, Nehru Road, Vile Parle E...",7460,"[{'lat': 19.09623, 'lng': 72.85419}]",19.09623,72.85419,400099,"[{'phone': [{'value': '+919664666457'}], 'www'...",here:pds:place:356te7u9-956d7d7d767748078ab88e...
15,LOTUS Colony Aarogy Kendra,"LOTUS Colony Aarogy Kendra, Shivaji Nagar-Lotu...",7691,"[{'lat': 19.06424, 'lng': 72.91839}]",19.06441,72.91849,400043,NaN,here:pds:place:356te7u7-3cf7a09df2294d679aa603...
16,La Maison Hospitality,"La Maison Hospitality, 1 Parleshwar Marg, Navp...",7937,"[{'lat': 19.10195, 'lng': 72.84543}]",19.10186,72.84553,400057,"[{'phone': [{'value': '+919930122614'}], 'www'...",here:pds:place:356te7u9-d7b0a51c06674bbebbb9cb...
17,Oshi,"Oshi, Oshiwara, Jogeshwari West, Mumbai 400102...",7956,"[{'lat': 19.14885, 'lng': 72.83944}]",19.14881,72.83934,400102,NaN,here:pds:place:356te7uc-7a52de251c97490b875666...
18,BBJ Verona Proposed,"BBJ Verona Proposed, Oshiwara, Jogeshwari West...",7991,"[{'lat': 19.14886, 'lng': 72.8389}]",19.14887,72.83901,400102,NaN,here:pds:place:356te7uc-70596e9c0e29441e8897bb...
19,Bhagat Enterprises,"Bhagat Enterprises, Gagangiri Maharaj Marg, Se...",8056,"[{'lat': 19.12502, 'lng': 72.98942}]",19.12503,72.98947,400701,[{'phone': [{'value': '+919987140408'}]}],here:pds:place:356te7uu-e5b5ef67de46464d94b444...

In [19]:
#Counting no. of cafes, department stores and gyms near apartments around IIT Bombay
df_final=d2[['position.lat','position.lng']]

CafeList=[]
ResList=[]
GymList=[]
latitudes = list(d2['position.lat'])
longitudes = list( d2['position.lng'])
for lat, lng in zip(latitudes, longitudes):    
    radius = '1000' #Set the radius to 1000 metres
    latitude=lat
    longitude=lng
    
    search_query = 'cafe' #Search for any cafes
    url = 'https://discover.search.hereapi.com/v1/discover?in=circle:{},{};r={}&q={}&apiKey=uJHMEjeagmFGldXp661-pDMf4R-PxvWIu7I68UjYC5Q'.format(latitude, longitude, radius, search_query)
    results = requests.get(url).json()
    venues=json_normalize(results['items'])
    CafeList.append(venues['title'].count())
	
    search_query = 'gym' #Search for any gyms
    url = 'https://discover.search.hereapi.com/v1/discover?in=circle:{},{};r={}&q={}&apiKey=uJHMEjeagmFGldXp661-pDMf4R-PxvWIu7I68UjYC5Q'.format(latitude, longitude, radius, search_query)
    results = requests.get(url).json()
    venues=json_normalize(results['items'])
    GymList.append(venues['title'].count())

    search_query = 'restaurents' #search for supermarkets
    url = 'https://discover.search.hereapi.com/v1/discover?in=circle:{},{};r={}&q={}&apiKey=uJHMEjeagmFGldXp661-pDMf4R-PxvWIu7I68UjYC5Q'.format(latitude, longitude, radius, search_query)
    results = requests.get(url).json()
    venues=json_normalize(results['items'])
    ResList.append(venues['title'].count())

df_final['Cafes'] = CafeList
df_final['Restaurents'] = ResList
df_final['Gyms'] = GymList

df_final

    position.lat  position.lng  Cafes  Restaurents  Gyms
0       19.12548      72.91935     11           20    18
1       19.12339      72.91274     20           20    20
2       19.11933      72.91227     20           20    20
3       19.11746      72.88374      8           20    20
4       19.16278      72.93287      4           20     7
5       19.09590      72.91356     16           20    18
6       19.11167      72.87505     15           20    20
7       19.16650      72.95585      6           20    20
8       19.07814      72.91175     15           20    20
9       19.17180      72.95568      7           20    20
10      19.16285      72.85787      7           20    15
11      19.12396      72.84676     10           20    20
12      19.14620      72.84590      4           20     9
13      19.10781      72.84909     18           20    20
14      19.09623      72.85419     16           20    18
15      19.06441      72.91849      1           20    13
16      19.10186      72.84553     20           20    20
17      19.14881      72.83934     17           20    20
18      19.14887      72.83901     18           20    20
19      19.12503      72.98947      1           20     2

In [20]:
#Run K-means clustering on dataframe
kclusters = 3

kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(df_final)
df_final['Cluster']=kmeans.labels_
df_final['Cluster']=df_final['Cluster'].apply(str)
df_final

    position.lat  position.lng  Cafes  Restaurents  Gyms Cluster
0       19.12548      72.91935     11           20    18       2
1       19.12339      72.91274     20           20    20       1
2       19.11933      72.91227     20           20    20       1
3       19.11746      72.88374      8           20    20       2
4       19.16278      72.93287      4           20     7       0
5       19.09590      72.91356     16           20    18       1
6       19.11167      72.87505     15           20    20       1
7       19.16650      72.95585      6           20    20       2
8       19.07814      72.91175     15           20    20       1
9       19.17180      72.95568      7           20    20       2
10      19.16285      72.85787      7           20    15       2
11      19.12396      72.84676     10           20    20       2
12      19.14620      72.84590      4           20     9       0
13      19.10781      72.84909     18           20    20       1
14      19.09623      72.85419     16           20    18       1
15      19.06441      72.91849      1           20    13       0
16      19.10186      72.84553     20           20    20       1
17      19.14881      72.83934     17           20    20       1
18      19.14887      72.83901     18           20    20       1
19      19.12503      72.98947      1           20     2       0

In [22]:
#Plotting clustered locations on map using Folium

#define coordinates of the college
map_bom=folium.Map(location=[19.1334,72.9133],zoom_start=12)

# instantiate a feature group for the incidents in the dataframe
locations = folium.map.FeatureGroup()

# set color scheme for the clusters
def color_producer(cluster):
    if cluster=='0':
        return 'green'
    elif cluster=='1':
        return 'orange'
    else:
        return 'red'

latitudes = list(df_final['position.lat'])
longitudes = list(df_final['position.lng'])
labels = list(df_final['Cluster'])
names=list(d2['title'])
for lat, lng, label,names in zip(latitudes, longitudes, labels,names):
    folium.CircleMarker(
            [lat,lng],
            fill=True,
            fill_opacity=1,
            popup=folium.Popup(names, max_width = 300),
            radius=5,
            color=color_producer(label)
        ).add_to(map_bom)

# add locations to map
map_bom.add_child(locations)
folium.Marker([19.1334,72.9133],popup='IIT Bombay').add_to(map_bom)

In [23]:
#saving the map 
map_bom.save("map-IITBombay.html")